const express = require("express");
const cors = require("cors");
const multer = require("multer");
const { createClient } = require("@supabase/supabase-js");
const { initializeApp, cert } = require("firebase-admin/app");
const { getFirestore, FieldValue, Timestamp } = require("firebase-admin/firestore");
const { getAuth } = require("firebase-admin/auth");
const { getMessaging } = require("firebase-admin/messaging");
const fetch = require("node-fetch");
const serviceAccount = require("./serviceAccountKey.json");

initializeApp({ credential: cert(serviceAccount) });
const db = getFirestore();
const auth = getAuth();

const supabase = createClient(
  process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_KEY
    );
    const SUPABASE_BUCKET = "pmmp-files";

    const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 200 * 1024 * 1024 } });

    const app = express();
    app.use(cors());
    app.use(express.json());

    async function verifyUser(req, res, next) {
      const idToken = req.headers.authorization?.replace("Bearer ", "");
        if (!idToken) return res.status(401).json({ error: "No autenticado." });
          try {
              const decoded = await auth.verifyIdToken(idToken);
                  req.uid = decoded.uid;
                      next();
                        } catch (e) {
                            res.status(401).json({ error: "Token inválido." });
                              }
                              }

                              app.post("/uploadFile", verifyUser, upload.single("file"), async (req, res) => {
                                try {
                                    if (!req.file) return res.status(400).json({ error: "No se recibió ningún archivo." });

                                        console.log(`[uploadFile] Recibido: ${req.file.originalname}, tamaño: ${req.file.size} bytes`);

                                            const folder = req.body.folder || "misc";
                                                const safeName = req.file.originalname.replace(/[^a-zA-Z0-9._-]/g, "_");
                                                    const path = `${req.uid}/${folder}/${Date.now()}_${safeName}`;

                                                        const { error } = await supabase.storage
                                                              .from(SUPABASE_BUCKET)
                                                                    .upload(path, req.file.buffer, { contentType: req.file.mimetype });

                                                                        if (error) {
                                                                              console.error("[uploadFile] Error de Supabase:", error.message);
                                                                                    return res.status(500).json({ error: error.message });
                                                                                        }

                                                                                            const { data } = supabase.storage.from(SUPABASE_BUCKET).getPublicUrl(path);
                                                                                                console.log(`[uploadFile] Éxito: ${data.publicUrl}`);
                                                                                                    res.json({ url: data.publicUrl });
                                                                                                      } catch (e) {
                                                                                                          console.error("[uploadFile] Error general:", e.message);
                                                                                                              res.status(500).json({ error: e.message });
                                                                                                                }
                                                                                                                });

                                                                                                                app.get("/testFirestore", async (req, res) => {
                                                                                                                  try {
                                                                                                                      await db.collection("_test").doc("ping").set({ time: new Date().toISOString() });
                                                                                                                          res.send("✅ Firestore funciona correctamente.");
                                                                                                                            } catch (e) {
                                                                                                                                res.status(500).send("❌ Error de Firestore: " + e.message);
                                                                                                                                  }
                                                                                                                                  });

                                                                                                                                  // ---------- PUSH NOTIFICATIONS ----------
                                                                                                                                  async function sendPushNotification(userId, title, body) {
                                                                                                                                    try {
                                                                                                                                        const userDoc = await db.collection("users").doc(userId).get();
                                                                                                                                            const token = userDoc.data()?.fcmToken;
                                                                                                                                                if (!token) return;
                                                                                                                                                    await getMessaging().send({ token, notification: { title, body } });
                                                                                                                                                      } catch (e) {
                                                                                                                                                          console.error("Error enviando notificación:", e.message);
                                                                                                                                                            }
                                                                                                                                                            }

                                                                                                                                                            // ---------- PAYPAL ----------
                                                                                                                                                            const PAYPAL_CLIENT_ID = process.env.PAYPAL_CLIENT_ID;
                                                                                                                                                            const PAYPAL_SECRET = process.env.PAYPAL_SECRET;
                                                                                                                                                            const PAYPAL_MODE = process.env.PAYPAL_MODE || "sandbox";
                                                                                                                                                            const PAYPAL_BASE =
                                                                                                                                                              PAYPAL_MODE === "live" ? "https://api-m.paypal.com" : "https://api-m.sandbox.paypal.com";

                                                                                                                                                              const PLAN_PRICES = {
                                                                                                                                                                hierro: { price: "4.99", months: 1 },
                                                                                                                                                                  oro: { price: "9.99", months: 3 },
                                                                                                                                                                    diamante: { price: "19.99", months: 6 },
                                                                                                                                                                    };
                                                                                                                                                                    const FEATURE_PRICE = "1.99";

                                                                                                                                                                    async function getPayPalAccessToken() {
                                                                                                                                                                      const authHeader = Buffer.from(`${PAYPAL_CLIENT_ID}:${PAYPAL_SECRET}`).toString("base64");
                                                                                                                                                                        const res = await fetch(`${PAYPAL_BASE}/v1/oauth2/token`, {
                                                                                                                                                                            method: "POST",
                                                                                                                                                                                headers: { Authorization: `Basic ${authHeader}`, "Content-Type": "application/x-www-form-urlencoded" },
                                                                                                                                                                                    body: "grant_type=client_credentials",
                                                                                                                                                                                      });
                                                                                                                                                                                        const data = await res.json();
                                                                                                                                                                                          return data.access_token;
                                                                                                                                                                                          }

                                                                                                                                                                                          app.post("/createPayPalOrder", verifyUser, async (req, res) => {
                                                                                                                                                                                            try {
                                                                                                                                                                                                const { type, planId, productId } = req.body;
                                                                                                                                                                                                    let amount, description;

                                                                                                                                                                                                        if (type === "plan") {
                                                                                                                                                                                                              const plan = PLAN_PRICES[planId];
                                                                                                                                                                                                                    if (!plan) return res.status(400).json({ error: "Plan inválido." });
                                                                                                                                                                                                                          amount = plan.price;
                                                                                                                                                                                                                                description = `Plan ${planId} - PocketMine Maps And Plugins`;
                                                                                                                                                                                                                                    } else if (type === "feature") {
                                                                                                                                                                                                                                          amount = FEATURE_PRICE;
                                                                                                                                                                                                                                                description = "Destacar publicación 1 semana";
                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                          return res.status(400).json({ error: "Tipo inválido." });
                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                  const accessToken = await getPayPalAccessToken();
                                                                                                                                                                                                                                                                      const orderRes = await fetch(`${PAYPAL_BASE}/v2/checkout/orders`, {
                                                                                                                                                                                                                                                                            method: "POST",
                                                                                                                                                                                                                                                                                  headers: { "Content-Type": "application/json", Authorization: `Bearer ${accessToken}` },
                                                                                                                                                                                                                                                                                        body: JSON.stringify({
                                                                                                                                                                                                                                                                                                intent: "CAPTURE",
                                                                                                                                                                                                                                                                                                        purchase_units: [{ amount: { currency_code: "USD", value: amount }, description }],
                                                                                                                                                                                                                                                                                                                application_context: {
                                                                                                                                                                                                                                                                                                                          return_url: "https://pocketminemapsandplugins.app/paypal/success",
                                                                                                                                                                                                                                                                                                                                    cancel_url: "https://pocketminemapsandplugins.app/paypal/cancel",
                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                  }),
                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                          const order = await orderRes.json();
                                                                                                                                                                                                                                                                                                                                                              const approveLink = order.links.find((l) => l.rel === "approve").href;

                                                                                                                                                                                                                                                                                                                                                                  await db.collection("pendingOrders").doc(order.id).set({
                                                                                                                                                                                                                                                                                                                                                                        userId: req.uid,
                                                                                                                                                                                                                                                                                                                                                                              type,
                                                                                                                                                                                                                                                                                                                                                                                    planId: planId || null,
                                                                                                                                                                                                                                                                                                                                                                                          productId: productId || null,
                                                                                                                                                                                                                                                                                                                                                                                                amount,
                                                                                                                                                                                                                                                                                                                                                                                                      description,
                                                                                                                                                                                                                                                                                                                                                                                                            status: "CREATED",
                                                                                                                                                                                                                                                                                                                                                                                                                  createdAt: FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                          res.json({ orderId: order.id, approveUrl: approveLink });
                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                res.status(500).json({ error: e.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                  app.post("/capturePayPalOrder", verifyUser, async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                        const { orderId, productId } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                            const orderDoc = await db.collection("pendingOrders").doc(orderId).get();
                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!orderDoc.exists) return res.status(404).json({ error: "Orden no encontrada." });

                                                                                                                                                                                                                                                                                                                                                                                                                                                    const orderData = orderDoc.data();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (orderData.userId !== req.uid) return res.status(403).json({ error: "No autorizado." });

                                                                                                                                                                                                                                                                                                                                                                                                                                                            const accessToken = await getPayPalAccessToken();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const captureRes = await fetch(`${PAYPAL_BASE}/v2/checkout/orders/${orderId}/capture`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            headers: { "Content-Type": "application/json", Authorization: `Bearer ${accessToken}` },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const captureData = await captureRes.json();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (captureData.status !== "COMPLETED") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await db.collection("pendingOrders").doc(orderId).update({ status: "FAILED" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return res.status(400).json({ error: "El pago no se completó." });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (orderData.type === "plan") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const plan = PLAN_PRICES[orderData.planId];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const expiresAt = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              expiresAt.setMonth(expiresAt.getMonth() + plan.months);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await db.collection("users").doc(req.uid).set(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { activePlan: orderData.planId, planExpiresAt: Timestamp.fromDate(expiresAt) },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    { merge: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await sendPushNotification(req.uid, "¡Plan activado! 🎉", `Tu plan ${orderData.planId} ya está activo. ¡A vender!`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else if (orderData.type === "feature") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const realProductId = productId || orderData.productId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await joinFeatureQueue(req.uid, realProductId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await sendPushNotification(req.uid, "¡Pago confirmado! 🎉", "Tu producto ya está en la fila para destacarse.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const productDoc = await db.collection("products").doc(realProductId).get();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const sellerId = productDoc.data()?.sellerId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (sellerId && sellerId !== req.uid) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await sendPushNotification(sellerId, "¡Tu producto fue destacado! 🌟", `"${productDoc.data()?.title}" fue destacado en el carrusel.`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              await db.collection("sales").add({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sellerId: req.uid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          productId: productId || orderData.productId || null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                productTitle: orderData.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      buyerId: req.uid,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            amount: orderData.amount,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  createdAt: FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await db.collection("pendingOrders").doc(orderId).update({ status: "COMPLETED" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ error: e.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      async function joinFeatureQueue(userId, productId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const activeSlotsSnap = await db.collection("carouselSlots").where("status", "==", "active").get();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const queueSnap = await db.collection("featureQueue").orderBy("joinedAt", "asc").get();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (activeSlotsSnap.size < 5 && queueSnap.empty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const expiresAt = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    expiresAt.setDate(expiresAt.getDate() + 3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await db.collection("carouselSlots").add({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              userId, productId, status: "active",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    expiresAt: Timestamp.fromDate(expiresAt),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          createdAt: FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await db.collection("featureQueue").add({ userId, productId, joinedAt: FieldValue.serverTimestamp() });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      app.post("/joinFeatureQueue", verifyUser, async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await joinFeatureQueue(req.uid, req.body.productId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          app.get("/processFeatureQueue", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const now = Timestamp.now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const expiredSlots = await db.collection("carouselSlots").where("status", "==", "active").where("expiresAt", "<=", now).get();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (const slotDoc of expiredSlots.docs) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await slotDoc.ref.update({ status: "expired" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const nextInQueueSnap = await db.collection("featureQueue").orderBy("joinedAt", "asc").limit(1).get();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!nextInQueueSnap.empty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const nextDoc = nextInQueueSnap.docs[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const nextData = nextDoc.data();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const expiresAt = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    expiresAt.setDate(expiresAt.getDate() + 3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await db.collection("carouselSlots").add({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  userId: nextData.userId, productId: nextData.productId, status: "active",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expiresAt: Timestamp.fromDate(expiresAt), createdAt: FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await nextDoc.ref.delete();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.json({ processed: expiredSlots.size });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              app.get("/", (req, res) => res.send("PMMP Server activo ✅"));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const PORT = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              app.listen(PORT, () => console.log(`Servidor corriendo en puerto ${PORT}`));