const express = require("express");
const cors = require("cors");
const admin = require("firebase-admin");
const fetch = require("node-fetch");
const serviceAccount = require("./serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  });
  const db = admin.firestore();

  const app = express();
  app.use(cors());
  app.use(express.json());

  const PAYPAL_CLIENT_ID = process.env.PAYPAL_CLIENT_ID;
  const PAYPAL_SECRET = process.env.PAYPAL_SECRET;
  const PAYPAL_MODE = process.env.PAYPAL_MODE || "sandbox";
  const PAYPAL_BASE =
    PAYPAL_MODE === "live"
        ? "https://api-m.paypal.com"
            : "https://api-m.sandbox.paypal.com";

            const PLAN_PRICES = {
              hierro: { price: "4.99", months: 1 },
                oro: { price: "9.99", months: 3 },
                  diamante: { price: "19.99", months: 6 },
                  };
                  const FEATURE_PRICE = "1.99";

                  async function getPayPalAccessToken() {
                    const auth = Buffer.from(`${PAYPAL_CLIENT_ID}:${PAYPAL_SECRET}`).toString("base64");
                      const res = await fetch(`${PAYPAL_BASE}/v1/oauth2/token`, {
                          method: "POST",
                              headers: {
                                    Authorization: `Basic ${auth}`,
                                          "Content-Type": "application/x-www-form-urlencoded",
                                              },
                                                  body: "grant_type=client_credentials",
                                                    });
                                                      const data = await res.json();
                                                        return data.access_token;
                                                        }

                                                        async function verifyUser(req, res, next) {
                                                          const idToken = req.headers.authorization?.replace("Bearer ", "");
                                                            if (!idToken) return res.status(401).json({ error: "No autenticado." });
                                                              try {
                                                                  const decoded = await admin.auth().verifyIdToken(idToken);
                                                                      req.uid = decoded.uid;
                                                                          next();
                                                                            } catch (e) {
                                                                                res.status(401).json({ error: "Token inválido." });
                                                                                  }
                                                                                  }

                                                                                  app.post("/createPayPalOrder", verifyUser, async (req, res) => {
                                                                                    try {
                                                                                        const { type, planId } = req.body;
                                                                                            let amount, description;

                                                                                                if (type === "plan") {
                                                                                                      const plan = PLAN_PRICES[planId];
                                                                                                            if (!plan) return res.status(400).json({ error: "Plan inválido." });
                                                                                                                  amount = plan.price;
                                                                                                                        description = `Plan ${planId} - PocketMine Maps And Plugins`;
                                                                                                                            } else if (type === "feature") {
                                                                                                                                  amount = FEATURE_PRICE;
                                                                                                                                        description = "Destacar publicación 1 semana";
                                                                                                                                            } else {
                                                                                                                                                  return res.status(400).json({ error: "Tipo inválido." });
                                                                                                                                                      }

                                                                                                                                                          const accessToken = await getPayPalAccessToken();
                                                                                                                                                              const orderRes = await fetch(`${PAYPAL_BASE}/v2/checkout/orders`, {
                                                                                                                                                                    method: "POST",
                                                                                                                                                                          headers: {
                                                                                                                                                                                  "Content-Type": "application/json",
                                                                                                                                                                                          Authorization: `Bearer ${accessToken}`,
                                                                                                                                                                                                },
                                                                                                                                                                                                      body: JSON.stringify({
                                                                                                                                                                                                              intent: "CAPTURE",
                                                                                                                                                                                                                      purchase_units: [{ amount: { currency_code: "USD", value: amount }, description }],
                                                                                                                                                                                                                              application_context: {
                                                                                                                                                                                                                                        return_url: "https://pocketminemapsandplugins.app/paypal/success",
                                                                                                                                                                                                                                                  cancel_url: "https://pocketminemapsandplugins.app/paypal/cancel",
                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                }),
                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                        const order = await orderRes.json();
                                                                                                                                                                                                                                                                            const approveLink = order.links.find((l) => l.rel === "approve").href;

                                                                                                                                                                                                                                                                                await db.collection("pendingOrders").doc(order.id).set({
                                                                                                                                                                                                                                                                                      userId: req.uid,
                                                                                                                                                                                                                                                                                            type,
                                                                                                                                                                                                                                                                                                  planId: planId || null,
                                                                                                                                                                                                                                                                                                        amount,
                                                                                                                                                                                                                                                                                                              status: "CREATED",
                                                                                                                                                                                                                                                                                                                    createdAt: admin.firestore.FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                            res.json({ orderId: order.id, approveUrl: approveLink });
                                                                                                                                                                                                                                                                                                                              } catch (e) {
                                                                                                                                                                                                                                                                                                                                  res.status(500).json({ error: e.message });
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                    app.post("/capturePayPalOrder", verifyUser, async (req, res) => {
                                                                                                                                                                                                                                                                                                                                      try {
                                                                                                                                                                                                                                                                                                                                          const { orderId, productId } = req.body;
                                                                                                                                                                                                                                                                                                                                              const orderDoc = await db.collection("pendingOrders").doc(orderId).get();
                                                                                                                                                                                                                                                                                                                                                  if (!orderDoc.exists) return res.status(404).json({ error: "Orden no encontrada." });

                                                                                                                                                                                                                                                                                                                                                      const orderData = orderDoc.data();
                                                                                                                                                                                                                                                                                                                                                          if (orderData.userId !== req.uid) return res.status(403).json({ error: "No autorizado." });

                                                                                                                                                                                                                                                                                                                                                              const accessToken = await getPayPalAccessToken();
                                                                                                                                                                                                                                                                                                                                                                  const captureRes = await fetch(`${PAYPAL_BASE}/v2/checkout/orders/${orderId}/capture`, {
                                                                                                                                                                                                                                                                                                                                                                        method: "POST",
                                                                                                                                                                                                                                                                                                                                                                              headers: { "Content-Type": "application/json", Authorization: `Bearer ${accessToken}` },
                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                      const captureData = await captureRes.json();

                                                                                                                                                                                                                                                                                                                                                                                          if (captureData.status !== "COMPLETED") {
                                                                                                                                                                                                                                                                                                                                                                                                await db.collection("pendingOrders").doc(orderId).update({ status: "FAILED" });
                                                                                                                                                                                                                                                                                                                                                                                                      return res.status(400).json({ error: "El pago no se completó." });
                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                              if (orderData.type === "plan") {
                                                                                                                                                                                                                                                                                                                                                                                                                    const plan = PLAN_PRICES[orderData.planId];
                                                                                                                                                                                                                                                                                                                                                                                                                          const expiresAt = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                expiresAt.setMonth(expiresAt.getMonth() + plan.months);
                                                                                                                                                                                                                                                                                                                                                                                                                                      await db.collection("users").doc(req.uid).set(
                                                                                                                                                                                                                                                                                                                                                                                                                                              {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        activePlan: orderData.planId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  planExpiresAt: admin.firestore.Timestamp.fromDate(expiresAt),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { merge: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (orderData.type === "feature") {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await joinFeatureQueue(req.uid, productId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await db.collection("pendingOrders").doc(orderId).update({ status: "COMPLETED" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ error: e.message });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      async function joinFeatureQueue(userId, productId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const activeSlotsSnap = await db.collection("carouselSlots").where("status", "==", "active").get();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const queueSnap = await db.collection("featureQueue").orderBy("joinedAt", "asc").get();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (activeSlotsSnap.size < 5 && queueSnap.empty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const expiresAt = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    expiresAt.setDate(expiresAt.getDate() + 3);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await db.collection("carouselSlots").add({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              userId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    productId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          status: "active",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expiresAt: admin.firestore.Timestamp.fromDate(expiresAt),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      createdAt: admin.firestore.FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await db.collection("featureQueue").add({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      userId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            productId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  joinedAt: admin.firestore.FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.post("/joinFeatureQueue", verifyUser, async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          await joinFeatureQueue(req.uid, req.body.productId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({ success: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            app.get("/processFeatureQueue", async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const now = admin.firestore.Timestamp.now();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const expiredSlots = await db
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .collection("carouselSlots")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .where("status", "==", "active")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .where("expiresAt", "<=", now)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .get();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (const slotDoc of expiredSlots.docs) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      await slotDoc.ref.update({ status: "expired" });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const nextInQueueSnap = await db.collection("featureQueue").orderBy("joinedAt", "asc").limit(1).get();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!nextInQueueSnap.empty) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const nextDoc = nextInQueueSnap.docs[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const nextData = nextDoc.data();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const expiresAt = new Date();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      expiresAt.setDate(expiresAt.getDate() + 3);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await db.collection("carouselSlots").add({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    userId: nextData.userId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            productId: nextData.productId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    status: "active",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expiresAt: admin.firestore.Timestamp.fromDate(expiresAt),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    createdAt: admin.firestore.FieldValue.serverTimestamp(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await nextDoc.ref.delete();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json({ processed: expiredSlots.size });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.get("/", (req, res) => res.send("PMMP Server activo ✅"));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const PORT = process.env.PORT || 3000;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.listen(PORT, () => console.log(`Servidor corriendo en puerto ${PORT}`));